# Generated by Django 2.2.2 on 2019-06-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifiactionmsg',
            new_name='notificationmsg',
        ),
    ]
