# Generated by Django 2.2.2 on 2019-06-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0002_auto_20190627_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('refno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sendername', models.CharField(max_length=50)),
                ('senderaddress', models.TextField()),
                ('sendermobno', models.CharField(max_length=15)),
                ('receivername', models.CharField(max_length=50)),
                ('receiveraddress', models.TextField()),
                ('receivermobno', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=10)),
                ('charge', models.IntegerField()),
                ('posteddate', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
